using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Euler
{

    /* Project Euler problem 2:
     * 
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
     * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... 
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     * 
     */
    class Problem_2
    {
        public static void run()
        {
            FibPair fibSequence = new FibPair(1);
            long result = 0;

            while (fibSequence.current < 4000000)
            {
                // Filter for even values by remainder
                if (fibSequence.current % 2 == 0)
                {
                    result += fibSequence.current;
                }

                // Create the next value in the sequence, update the sequence
                fibSequence.updatePair(fibSequence.current + fibSequence.old);
                
            }

            Console.Write("Result = " + result + " ");
        }
    }

    // Class to hold the current and previous value to make the additions easier
    class FibPair
    {
        public int current;
        public int old;

        public FibPair(int val)
        {
            current = val;
            old = val;
        }

        // Replace the previous value with the current value, replace current value with new value
        public void updatePair(int newVal){
            old = current;
            current = newVal;
        }
    }
}
